site_name: Data Engineer Project Docs
theme:
  name: material

nav:
  - Home: README.md
  - Theory:
      - Data Sources: theory/data_sources.md
      - Data Engineering Principles: theory/data_eng_principles.md
  - Project Notes:
      - Project Roadmap: notes/project_roadmap.md
      - Design Decisions: notes/design_decisions.md
  - Code Explanations:
      - ETL Pipeline: code/etl_pipeline.md
      - Storage Strategy: code/storage.md